/** * rejuvenation-audio.js * Axis Lumen Studio — Playlists audio du parcours Rajeunissement Cellulaire * * Intègre les fichiers audio issus du dossier : * app/modules/rajeunissement/sound/ * * Ces pistes sont organisées en playlists défilantes par thématique. * Aucune référence externe : nomenclature propre à Axis Lumen. */ // ─── Chemins de base ─────────────────────────────────────────────────────────
// Adapter BASE_PATH à l'arborescence de déploiement réelle.
const BASE_PATH = '/modules/rajeunissement/sound/'; // ─── Catalogue des pistes audio ──────────────────────────────────────────────
//
// Chaque piste est décrite par :
// id : identifiant unique
// label : nom affiché dans l'interface
// file : nom du fichier dans le dossier sound/
// category : thématique (utilisée pour filtrer / regrouper)
// duration : durée indicative en secondes (0 = inconnue)
//
// ⚠️ Mettre à jour cette liste avec les noms de fichiers réels présents dans
// C:\Users\chauv\Documents\AXIS LUMEN\Axis Lumen site internet 13 bis\app\modules\rajeunissement\sound
//
export const REJUVENATION_TRACKS = [ // — Séquences de base — { id: 'rej-01', label: 'Ancrage & Vitalité', file: '01_ancrage_vitalite.mp3', category: 'fondation', duration: 0 }, { id: 'rej-02', label: 'Activation Cellulaire', file: '02_activation_cellulaire.mp3', category: 'fondation', duration: 0 }, { id: 'rej-03', label: 'Harmonisation Énergétique', file: '03_harmonisation.mp3', category: 'equilibre', duration: 0 }, { id: 'rej-04', label: 'Régénération Profonde', file: '04_regeneration.mp3', category: 'equilibre', duration: 0 }, { id: 'rej-05', label: 'Renouvellement Tissulaire', file: '05_renouvellement.mp3', category: 'restauration', duration: 0 }, { id: 'rej-06', label: 'Détoxication & Clarté', file: '06_detoxication.mp3', category: 'restauration', duration: 0 }, { id: 'rej-07', label: 'Circulation & Fluidité', file: '07_circulation.mp3', category: 'vitalite', duration: 0 }, { id: 'rej-08', label: 'Équilibre Hormonal', file: '08_equilibre_hormonal.mp3', category: 'vitalite', duration: 0 }, { id: 'rej-09', label: 'Jeunesse Cellulaire', file: '09_jeunesse_cellulaire.mp3', category: 'avance', duration: 0 }, { id: 'rej-10', label: 'Longévité & Sérénité', file: '10_longevite.mp3', category: 'avance', duration: 0 },
]; // ─── Playlists défilantes prédéfinies ───────────────────────────────────────── export const REJUVENATION_PLAYLISTS = [ { id: 'playlist-decouverte', label: 'Découverte — 3 séances', description: 'Introduction progressive au parcours de rajeunissement.', tracks: ['rej-01', 'rej-03', 'rej-07'], }, { id: 'playlist-fondation', label: 'Fondation — Bases essentielles', description: 'Ancrage, activation et harmonisation pour poser les bases.', tracks: ['rej-01', 'rej-02', 'rej-03'], }, { id: 'playlist-restauration', label: 'Restauration — Récupération cellulaire', description: 'Séquence axée sur la détoxication et le renouvellement tissulaire.', tracks: ['rej-05', 'rej-06', 'rej-04'], }, { id: 'playlist-vitalite', label: 'Vitalité — Énergie & Circulation', description: 'Soutien de la circulation et de l\'équilibre hormonal.', tracks: ['rej-07', 'rej-08', 'rej-02'], }, { id: 'playlist-integrale', label: 'Intégrale — Parcours complet', description: 'Les 10 pistes dans l\'ordre recommandé pour un cycle complet.', tracks: REJUVENATION_TRACKS.map(t => t.id), }, { id: 'playlist-avance', label: 'Avancé — Longévité profonde', description: 'Séquence pour les pratiquants réguliers souhaitant aller plus loin.', tracks: ['rej-04', 'rej-09', 'rej-10', 'rej-08'], },
]; // ─── Résolution d'une piste par son id ─────────────────────────────────────── export function getTrackById(id) { return REJUVENATION_TRACKS.find(t => t.id === id) || null;
} // ─── Résolution d'une playlist par son id ──────────────────────────────────── export function getPlaylistById(id) { return REJUVENATION_PLAYLISTS.find(p => p.id === id) || null;
} // ─── Résolution complète d'une playlist (tracks résolues) ──────────────────── export function resolvePlaylist(playlistId) { const playlist = getPlaylistById(playlistId); if (!playlist) return null; return { ...playlist, resolvedTracks: playlist.tracks.map(id => getTrackById(id)).filter(Boolean), };
} // ─── Construction d'une URL audio complète ─────────────────────────────────── export function trackUrl(track) { return `${BASE_PATH}${track.file}`;
} // ─── Lecteur de playlist défilante ───────────────────────────────────────────
//
// Gère la lecture séquentielle automatique d'une playlist.
// Utilise la Web Audio API via un élément <audio> standard. export class PlaylistPlayer { constructor({ onTrackChange = null, onEnd = null } = {}) { this.audio = new Audio(); this.audio.preload = 'auto'; this.playlist = null; this.currentIndex = 0; this.onTrackChange = onTrackChange; this.onEnd = onEnd; this.audio.addEventListener('ended', () => this._onTrackEnded()); this.audio.addEventListener('error', (e) => console.warn('[PlaylistPlayer] Erreur audio :', e)); } /** Charge une playlist et démarre la lecture depuis la piste index. */ load(playlistId, startIndex = 0) { this.playlist = resolvePlaylist(playlistId); if (!this.playlist) { console.warn(`[PlaylistPlayer] Playlist introuvable : ${playlistId}`); return; } this.currentIndex = startIndex; this._playCurrentTrack(); } /** Lance / reprend la lecture. */ play() { if (this.audio.src) this.audio.play().catch(() => {}); } /** Met en pause. */ pause() { this.audio.pause(); } /** Arrête et réinitialise. */ stop() { this.audio.pause(); this.audio.currentTime = 0; } /** Passe à la piste suivante. */ next() { if (!this.playlist) return; this.currentIndex = (this.currentIndex + 1) % this.playlist.resolvedTracks.length; this._playCurrentTrack(); } /** Revient à la piste précédente. */ prev() { if (!this.playlist) return; this.currentIndex = (this.currentIndex - 1 + this.playlist.resolvedTracks.length) % this.playlist.resolvedTracks.length; this._playCurrentTrack(); } /** Saute directement à un index. */ goTo(index) { if (!this.playlist) return; this.currentIndex = Math.max(0, Math.min(index, this.playlist.resolvedTracks.length - 1)); this._playCurrentTrack(); } /** Piste en cours de lecture. */ get currentTrack() { if (!this.playlist) return null; return this.playlist.resolvedTracks[this.currentIndex] || null; } /** Progression de la playlist (0–1). */ get playlistProgress() { if (!this.playlist || !this.playlist.resolvedTracks.length) return 0; return this.currentIndex / this.playlist.resolvedTracks.length; } // — Interne — _playCurrentTrack() { const track = this.currentTrack; if (!track) return; const url = trackUrl(track); if (this.audio.src !== url) { this.audio.src = url; this.audio.load(); } this.audio.play().catch(() => {}); if (this.onTrackChange) this.onTrackChange(track, this.currentIndex); } _onTrackEnded() { if (!this.playlist) return; const isLast = this.currentIndex >= this.playlist.resolvedTracks.length - 1; if (isLast) { if (this.onEnd) this.onEnd(); } else { this.next(); } }
} // ─── Composant UI : rendu HTML d'une playlist défilante ─────────────────────
//
// Insère une liste de pistes dans un conteneur DOM avec :
// - indicateur de piste active
// - boutons Précédent / Lecture / Pause / Suivant
// - défilement automatique vers la piste en cours export function renderPlaylistUI(containerId, player) { const container = document.getElementById(containerId); if (!container) return; function render() { const playlist = player.playlist; if (!playlist) { container.innerHTML = '<p class="al-playlist-empty">Aucune playlist chargée.</p>'; return; } const tracks = playlist.resolvedTracks; const currentIdx = player.currentIndex; container.innerHTML = ` <div class="al-playlist"> <div class="al-playlist-header"> <h3 class="al-playlist-title">${playlist.label}</h3> <p class="al-playlist-desc">${playlist.description}</p> </div> <ul class="al-playlist-tracks" id="${containerId}-list"> ${tracks.map((track, i) => ` <li class="al-playlist-track ${i === currentIdx ? 'al-active' : ''}" data-index="${i}" title="${track.label}" > <span class="al-track-index">${String(i + 1).padStart(2, '0')}</span> <span class="al-track-label">${track.label}</span> ${i === currentIdx ? '<span class="al-track-playing-icon">▶</span>' : ''} </li> `).join('')} </ul> <div class="al-playlist-controls"> <button class="al-btn al-btn-prev" id="${containerId}-prev" aria-label="Précédent">⏮</button> <button class="al-btn al-btn-play" id="${containerId}-play" aria-label="Lecture">▶</button> <button class="al-btn al-btn-pause" id="${containerId}-pause" aria-label="Pause">⏸</button> <button class="al-btn al-btn-next" id="${containerId}-next" aria-label="Suivant">⏭</button> </div> </div> `; // Scroll automatique vers la piste active const list = document.getElementById(`${containerId}-list`); const activeItem = list?.querySelector('.al-active'); if (activeItem) activeItem.scrollIntoView({ behavior: 'smooth', block: 'nearest' }); // Clics sur les pistes list?.querySelectorAll('.al-playlist-track').forEach(el => { el.addEventListener('click', () => { const idx = parseInt(el.dataset.index, 10); player.goTo(idx); render(); }); }); // Contrôles document.getElementById(`${containerId}-prev`)?.addEventListener('click', () => { player.prev(); render(); }); document.getElementById(`${containerId}-play`)?.addEventListener('click', () => player.play()); document.getElementById(`${containerId}-pause`)?.addEventListener('click', () => player.pause()); document.getElementById(`${containerId}-next`)?.addEventListener('click', () => { player.next(); render(); }); } // Ré-affichage à chaque changement de piste player.onTrackChange = () => render(); render();
} // ─── Initialisation rapide (usage simplifié) ─────────────────────────────────
//
// Exemple d'utilisation dans un module :
//
// import { initPlaylist } from './modules/rejuvenation-audio.js';
// const player = initPlaylist('playlist-integrale', 'al-playlist-container'); export function initPlaylist(playlistId, containerId, startIndex = 0) { const player = new PlaylistPlayer(); player.load(playlistId, startIndex); if (containerId) renderPlaylistUI(containerId, player); return player;
}
